### ISSUE TITLE
error at transfer.py

### ISSUE THREAD

**Issue by LelisThanos** [arpanmangal/CovidAID#4]
python3 tools/transfer.py --combine_pneumonia
Traceback (most recent call last):
  File "tools/transfer.py", line 45, in <module>
    assert len(c_keys.difference(t_keys)) == 0
AssertionError

**Comment by arpanmangal** [comment]
Please report your pytorch and torchvision versions. If not already doing, use the correct version of these packages as mentioned here: https://github.com/arpanmangal/CovidAID/blob/master/INSTALL.md
